import type { Metadata } from "next";
import "./globals.css";
import { k2d } from "./font";

export const metadata: Metadata = {
  title: "Product CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.className}`}>{children}</body>
    </html>
  );
}
