import type { Metadata } from "next";
import "../../globals.css";
import { k2d } from "../../font";
import AppHeader from "@/components/app/AppHeader";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
export const metadata: Metadata = {
  title: "SeaBite",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={`${k2d.className}`}>
        <AppHeader />
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
